.TH N\-COLORCODE 6
.SH NAME
n\-colorcode \- play the game of Mastermind/Colorcode in a terminal
.\"
.SH SYNOPSIS
\fBn-colorcode\fR [\fB\-c\fR] [\fB\-d\fR \fIdifficulty\fR]
.\"
.SH DESCRIPTION
desc
.\"
.SH OPTIONS
.TP
.B \-c
Cheat: Print the answer at the start of the game.
.TP
.B \-d
Difficulty: Set the difficulty.
This defaults to \fInormal\fR, and only changes the number of attempts.
Possible values are
.RS
\fInormal\fR \- 10 attempts
.nf
\fIhard\fR \- 7 attempts
\fIperfect\fR \- 5 attempts
.RE
.fi
.\"
.SH SEE ALSO
Source code is at \fIhttps://github.com/leapwill/n-colorcode\fR
